# Generated by Django 2.1.1 on 2018-10-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0002_deposite'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_no', models.IntegerField(default=10)),
                ('w_name', models.CharField(max_length=50)),
                ('w_money', models.IntegerField(default=10)),
                ('A_date', models.DateField()),
                ('A_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='deposite',
            old_name='A_money',
            new_name='D_money',
        ),
        migrations.RenameField(
            model_name='deposite',
            old_name='A_name',
            new_name='D_name',
        ),
        migrations.RenameField(
            model_name='deposite',
            old_name='A_no',
            new_name='D_no',
        ),
    ]
