# Generated by Django 2.1.1 on 2018-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0003_auto_20181019_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposite',
            name='id',
        ),
        migrations.AlterField(
            model_name='deposite',
            name='D_no',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
