# Generated by Django 2.1.1 on 2018-10-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('cno', models.IntegerField(default=10)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adds', models.CharField(max_length=100)),
            ],
        ),
    ]
