# Generated by Django 2.1.1 on 2018-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(default=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=50)),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
