# Generated by Django 2.1.1 on 2018-10-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.IntegerField(default=500),
        ),
    ]
