# Generated by Django 2.1.1 on 2018-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('entry', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('members', models.CharField(max_length=50)),
            ],
        ),
    ]
