# Generated by Django 2.1.1 on 2018-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.IntegerField(default=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=3)),
                ('fee', models.IntegerField(default=5)),
            ],
        ),
    ]
