# Generated by Django 2.1.1 on 2018-10-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('path', models.FilePathField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
