# Generated by Django 2.0.7 on 2018-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Contact', models.IntegerField(primary_key=True, serialize=False)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
