# Generated by Django 2.0.7 on 2018-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
